require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BrokeragesController do

  # This should return the minimal set of attributes required to create a valid
  # Brokerage. As you add validations to Brokerage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "company" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BrokeragesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all brokerages as @brokerages" do
      brokerage = Brokerage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:brokerages).should eq([brokerage])
    end
  end

  describe "GET show" do
    it "assigns the requested brokerage as @brokerage" do
      brokerage = Brokerage.create! valid_attributes
      get :show, {:id => brokerage.to_param}, valid_session
      assigns(:brokerage).should eq(brokerage)
    end
  end

  describe "GET new" do
    it "assigns a new brokerage as @brokerage" do
      get :new, {}, valid_session
      assigns(:brokerage).should be_a_new(Brokerage)
    end
  end

  describe "GET edit" do
    it "assigns the requested brokerage as @brokerage" do
      brokerage = Brokerage.create! valid_attributes
      get :edit, {:id => brokerage.to_param}, valid_session
      assigns(:brokerage).should eq(brokerage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Brokerage" do
        expect {
          post :create, {:brokerage => valid_attributes}, valid_session
        }.to change(Brokerage, :count).by(1)
      end

      it "assigns a newly created brokerage as @brokerage" do
        post :create, {:brokerage => valid_attributes}, valid_session
        assigns(:brokerage).should be_a(Brokerage)
        assigns(:brokerage).should be_persisted
      end

      it "redirects to the created brokerage" do
        post :create, {:brokerage => valid_attributes}, valid_session
        response.should redirect_to(Brokerage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved brokerage as @brokerage" do
        # Trigger the behavior that occurs when invalid params are submitted
        Brokerage.any_instance.stub(:save).and_return(false)
        post :create, {:brokerage => { "company" => "invalid value" }}, valid_session
        assigns(:brokerage).should be_a_new(Brokerage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Brokerage.any_instance.stub(:save).and_return(false)
        post :create, {:brokerage => { "company" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested brokerage" do
        brokerage = Brokerage.create! valid_attributes
        # Assuming there are no other brokerages in the database, this
        # specifies that the Brokerage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Brokerage.any_instance.should_receive(:update).with({ "company" => "MyString" })
        put :update, {:id => brokerage.to_param, :brokerage => { "company" => "MyString" }}, valid_session
      end

      it "assigns the requested brokerage as @brokerage" do
        brokerage = Brokerage.create! valid_attributes
        put :update, {:id => brokerage.to_param, :brokerage => valid_attributes}, valid_session
        assigns(:brokerage).should eq(brokerage)
      end

      it "redirects to the brokerage" do
        brokerage = Brokerage.create! valid_attributes
        put :update, {:id => brokerage.to_param, :brokerage => valid_attributes}, valid_session
        response.should redirect_to(brokerage)
      end
    end

    describe "with invalid params" do
      it "assigns the brokerage as @brokerage" do
        brokerage = Brokerage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Brokerage.any_instance.stub(:save).and_return(false)
        put :update, {:id => brokerage.to_param, :brokerage => { "company" => "invalid value" }}, valid_session
        assigns(:brokerage).should eq(brokerage)
      end

      it "re-renders the 'edit' template" do
        brokerage = Brokerage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Brokerage.any_instance.stub(:save).and_return(false)
        put :update, {:id => brokerage.to_param, :brokerage => { "company" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested brokerage" do
      brokerage = Brokerage.create! valid_attributes
      expect {
        delete :destroy, {:id => brokerage.to_param}, valid_session
      }.to change(Brokerage, :count).by(-1)
    end

    it "redirects to the brokerages list" do
      brokerage = Brokerage.create! valid_attributes
      delete :destroy, {:id => brokerage.to_param}, valid_session
      response.should redirect_to(brokerages_url)
    end
  end

end
